### ISSUE TITLE
Download counts broke again

### ISSUE THREAD

**Issue by kingthorin** [zapbot/zap-mgmt-scripts#33]
It seems something changed on the 17th:
```console
 stats/releases-2020-08-15.json            | 2460 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 stats/releases-2020-08-16.json            | 2460 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 stats/releases-2020-08-17.json            | 2460 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 stats/releases-2020-08-18.json            | 2222 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 stats/releases-2020-08-19.json            | 2222 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 stats/releases-2020-08-20.json            | 2222 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 stats/releases-2020-08-21.json            | 2222 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 stats/releases-2020-08-22.json            | 2222 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 stats/releases-2020-08-23.json            | 2222 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 stats/releases-2020-08-24.json            | 2222 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 stats/releases-2020-08-25.json            | 2222 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 stats/releases-2020-08-26.json            | 2222 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

And stats are no longer updating.
![image](https://user-images.githubusercontent.com/7570458/91245720-2db29400-e71c-11ea-9f51-cc6fde3c4ab6.png)

I suspect this might have to do with the number of releases and paging. Investigating.

**Comment by kingthorin** [comment]
So `https://api.github.com/repos/zaproxy/zaproxy/releases` only returns the latest 30. So apparently on the 18th we hit 30 weeklies since 2.9.0 I guess? (We could increase to `?perPage=100` but if we ever run into more than 100 weeklies we'd have the problem again).

We can get the stats on [2.9.0 specifically](https://api.github.com/repos/zaproxy/zaproxy/releases/tags/v2.9.0), however it's returned as a single object not an array of objects like the current script expects. So we have two options:
1. Start back at zero stats. Change the handling to a single object (I looked at this quickly removing the `for stat in stats:` loop, but then the one object is just treated as unicode instead of dict for some reason). 
2. Wrap the newer tag specific API response in `[,]` so that it's treated as a single item array and parsed into a dict. (The job could continue largely as-is, the columns in the graph would just jump from the 17th to whenever we pickup again.)

count-zap-downloads.py already has to be changed per release (for the new tag and asset names) so having to also change the API call in the workflow isn't a huge deal. (Compared to current. Though it could arguably be more elegant somehow, I just haven't put though into that.)

**Comment by kingthorin** [comment]
Something is still amiss. Will investigate further.

**Comment by thc202** [comment]
Closing with changes done in #36.
